name: Publish

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Upgrade pip
        run: pip install -U pip

      - name: Install poetry
        run: pip install -U poetry

      - name: Build
        run: poetry build

      - name: Publish
        env: 
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: poetry publish -u __token__ -p $PYPI_TOKEN
